name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.8", "3.10" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install tox

      - name: Run tox
        run: tox

  test-pip-install:
    name: Test pip install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v2

      - name: Build
        run: python setup.py sdist

      - name: Test 'pip install'
        run: pip install $(ls dist/saml_test_helper*.gz)
